# This is a basic workflow to help you get started with Actions

name: Build and Unit test

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the devel branch
  push:
    branches: [devel]
  pull_request:
    branches: [devel]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  install:
    runs-on: ubuntu-latest
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.5
      - run: npm i -g yarn || true # Not necessary on Github but useful to test locally with `act`
      - run: yarn install --frozen-lockfile --check-files

      # This workflow contains a single job called "build"
      #unit-test:
      # The type of runner that the job will run on
      #  runs-on: ubuntu-latest
      #  needs: install

      # Steps represent a sequence of tasks that will be executed as part of the job
      #  steps:
      - run: yarn run typecheck
      - run: yarn run test:unit

      #build:
      #  runs-on: ubuntu-latest
      #  needs: install
      #
      #    steps:
      - run: yarn run build
      # Runs a single command using the runners shell
      #- name: Run a one-line script
      #  run: echo Hello, world!
      # Runs a set of commands using the runners shell
      # - name: Run a multi-line script
      #  run: |
      #    echo Add other actions to build,
      #    echo test, and deploy your project.
